### ISSUE TITLE
UTF-8 width formatting

### ISSUE THREAD

**Issue by turnstep** [manvscode/timezoner#2]
People's names  (and presumably emails) that are UTF-8 cause incorrect formatting. Tracked this back to the use of sprintf with a fixed width (e.g. line 368), which of course only cares about bytes. This results in the output for a person named Alex Boyé, for example, having one character less than it ought to in the display, so their email is shifted left one character compared to the rest. One solution is to walk client->name and count number of high chars, then output that number of spaces. Not sure how/if UTF-8 names would affect some of the truncation strlen checks in that same section.

**Comment by manvscode** [comment]
This was more complicated than I imagined.  This *could* be fixed by commit 2482d67e4c878e06f21bdf4566bf23fd24a2fd40.

**Comment by turnstep** [comment]
Hm...still having issues when more than one UTF-8 at the end of a name/email.

**Comment by manvscode** [comment]
@turnstep Can you share your ~/.timezoner config file?   The think the problems stem from the variable width format specificier (i.e. "%*s") in printf().   The width that is passed is expected to be in bytes and not characters.  If you could the number of bytes in your UTF-8 string and use that number of bytes per column width then I think then the formatting gets messed up.

**Comment by turnstep** [comment]
Here's one that demonstrates both name and email problems:

America/New_York    "boris@nogoodnik.com"        "Boris Badenov" "" ""
Europe/London       "rocky@wallawalla.edu"       "Rocky" "" ""
Europe/London       "peachfuzz@military.mil"
 "ABCDEFGHIJKLMNOPQRSTUVWXYZñññ" "" ""
Europe/London       "bullwinkle@knowitall.cöñ"   "Bullwinkle J. Moose" "" ""

​

**Comment by manvscode** [comment]
@turnstep I'll look into this.

**Comment by manvscode** [comment]
@turnstep Hi Greg.  I migrated the string handling to use wide character strings.  I think this will resolve the problem where printf() formats are expecting byte lengths instead of UTF-8 string lengths.  

If you pull down the code, you have to do:
make clean_extern

Please let me know if this resolves this bug.

**Comment by turnstep** [comment]
Looks good to me! Consider this bug closed. :)
